/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : bigint,
  'storeId' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface Review {
  'productId' : bigint,
  'comment' : string,
  'rating' : bigint,
  'reviewer' : string,
}
export interface Store {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface _SERVICE {
  '_clearStoresForTesting' : ActorMethod<[], undefined>,
  'getAllStores' : ActorMethod<[], Array<Store>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByStore' : ActorMethod<[bigint], Array<Product>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'initialize' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<[Array<bigint>, Array<bigint>, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];