/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const OrderDetail = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'username' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(OrderItem),
});
export const Store = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'storeId' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const Review = IDL.Record({
  'productId' : IDL.Nat,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Text,
});

export const idlService = IDL.Service({
  '_clearStoresForTesting' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderDetail)], ['query']),
  'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrdersByUser' : IDL.Func([IDL.Text], [IDL.Vec(OrderDetail)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByStore' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Text],
      [],
    ),
  'placeOrderWithUser' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const OrderDetail = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'username' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(OrderItem),
  });
  const Store = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'storeId' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Review = IDL.Record({
    'productId' : IDL.Nat,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Text,
  });
  
  return IDL.Service({
    '_clearStoresForTesting' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderDetail)], ['query']),
    'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrdersByUser' : IDL.Func([IDL.Text], [IDL.Vec(OrderDetail)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByStore' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Text],
        [],
      ),
    'placeOrderWithUser' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };