/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Store = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'storeId' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const Review = IDL.Record({
  'productId' : IDL.Nat,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Text,
});

export const idlService = IDL.Service({
  '_clearStoresForTesting' : IDL.Func([], [], []),
  'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByStore' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Store = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'storeId' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Review = IDL.Record({
    'productId' : IDL.Nat,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Text,
  });
  
  return IDL.Service({
    '_clearStoresForTesting' : IDL.Func([], [], []),
    'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByStore' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };